### ISSUE TITLE
切换页面

### ISSUE THREAD

**Issue by NerdC** [upcyoung/muti-project#1]
你好，在查看你的项目示例的时候发现，我使用yarn start启动，无法切换到app1的模块，尝试过修改但未成功，请问你能解决这个问题吗？

**Comment by upcyoung** [comment]
这个示例含默认应用、app1、app2
run `yarn start` or `npm start`运行的是默认应用
run `yarn run app1` 启动app1

see `package.json` and `react.json`

**Comment by NerdC** [comment]
你还没明白我的意思 ，不过不重要 ，这个问题我已经解决了。
